TEXTS = {
    # "cs": """Důmyslný rytíř don Quijote de la Mancha (originální název z roku 1605 El ingenioso hidalgo Don Quixote de la Mancha''', později Don Quijote de la Mancha či též Don Quijote [don kichote]) je pravděpodobně nejslavnějším španělským románem a jedním z klíčových děl světové literatury. Jeho autorem je Miguel de Cervantes y Saavedra. Jedná se o román z období renesance, který uvedl do literatury komicky vyjádřený rozpor mezi skutečností a iluzí. V současné době je Don Quijote přeložen do 85 různých jazyků.[1][2] Daniel Defoe v předmluvě k třetímu dílu Robinsona Crusoe uvádí, že postava dona Quijota byla inspirována charakterem vévody de Medina Sidonia, Alonsa Péreze de Guzmána.[3] """,
    "de": """Don Quijote Zum Anhören bitte klicken!Abspielen [ˈdoŋ kiˈxɔte] (Don Quixote in alter Schreibweise; Don Quichotte [kiˈʃɔt] in französischer Orthografie, teilweise auch im deutschen Sprachraum verwendet) ist die allgemeinsprachliche Bezeichnung für den spanischsprachigen Roman El ingenioso hidalgo Don Quixote de la Mancha von Miguel de Cervantes, übersetzt Der sinnreiche Junker Don Quijote von der Mancha, und gleichzeitig der Name des Protagonisten. Der erste Teil wurde 1605 veröffentlicht, der zweite 1615 unter dem Titel Segunda parte del ingenioso caballero don Quixote de la Mancha.

Don Quijote ist ein seinen Ritterromanen verfallener Leser, der unfähig erscheint zwischen Dichtung und Wahrheit zu unterscheiden. Er hält sich für einen stolzen Ritter, dem vermeintlich das Schicksal ein kühnes Abenteuer nach dem nächsten zu bestreiten auferlegt. Er steigt auf sein klappriges Pferd Rosinante und kämpft unter anderem gegen Windmühlen. Treu an seiner Seite reitet der nur scheinbar naive Schildknappe Sancho Pansa und versucht, seinen Herrn vor schlimmerem Unheil zu bewahren. Meist enden die Episoden damit, dass Don Quijote verprügelt wird und wenig ruhmreich als „Ritter von der traurigen Gestalt“ auftritt. Im 1615 vorgelegten zweiten Teil ist der – immer noch verarmte – Landadelige Don Quijote eine literarische Berühmtheit geworden.
""",
    "en": """The Ingenious Gentleman Don Quixote of La Mancha (Modern Spanish: El ingenioso hidalgo (in Part 2, caballero) Don Quijote de la Mancha, pronounced [el iŋxeˈnjoso iˈðalɣo ðoŋ kiˈxote ðe la ˈmantʃa] (About this soundlisten)), or just Don Quixote (/ˌdɒn kiːˈhoʊti/, US: /-teɪ/;[1] Spanish: [doŋ kiˈxote] (About this soundlisten)), is a Spanish novel by Miguel de Cervantes. It was published in two parts, in 1605 and 1615. A founding work of Western literature, it is often labeled "the first modern novel"[2][3] and many authors consider it to be the best literary work ever written.[4][5]

The plot revolves around the adventures of a noble (hidalgo) from La Mancha named Alonso Quixano, who reads so many chivalric romances that he loses his mind and decides to become a knight-errant (caballero andante) to revive chivalry and serve his nation, under the name Don Quixote de la Mancha. He recruits a simple farmer, Sancho Panza, as his squire, who often employs a unique, earthy wit in dealing with Don Quixote's rhetorical monologues on knighthood, already considered old-fashioned at the time. Don Quixote, in the first part of the book, does not see the world for what it is and prefers to imagine that he is living out a knightly story.

The book had a major influence on the literary community, as evidenced by direct references in Alexandre Dumas' The Three Musketeers (1844), Mark Twain's Adventures of Huckleberry Finn (1884), and Edmond Rostand's Cyrano de Bergerac (1897), as well as the word quixotic and the epithet Lothario; the latter refers to a character in "El curioso impertinente" ("The Impertinently Curious Man"), an intercalated story that appears in Part One, chapters 33–35. The 19th-century German philosopher Arthur Schopenhauer cited Don Quixote as one of the four greatest novels ever written.[6]

When first published, Don Quixote was usually interpreted as a comic novel. After the French Revolution, it was better known for its central ethic that individuals can be right while society is quite wrong and seen as disenchanting. In the 19th century, it was seen as a social commentary, but no one could easily tell "whose side Cervantes was on". Many critics came to view the work as a tragedy in which Don Quixote's idealism and nobility are viewed by the post-chivalric world as insane, and are defeated and rendered useless by common reality. By the 20th century, the novel had come to occupy a canonical space as one of the foundations of modern literature. """,
    "es": """Don Quijote de la Manchaa es una novela escrita por el español Miguel de Cervantes Saavedra. Publicada su primera parte con el título de El ingenioso hidalgo don Quijote de la Mancha a comienzos de 1605, es la obra más destacada de la literatura española y una de las principales de la literatura universal, además de ser la más leída después de la Biblia.12 En 1615 apareció su continuación con el título de Segunda parte del ingenioso caballero don Quijote de la Mancha. El Quijote de 1605 se publicó dividido en cuatro partes; pero al aparecer el Quijote de 1615 en calidad de Segunda parte de la obra, quedó revocada de hecho la partición en cuatro secciones del volumen publicado diez años antes por Cervantes.3

Es la primera obra genuinamente desmitificadora de la tradición caballeresca y cortés por su tratamiento burlesco. Representa la primera novela moderna y la primera novela polifónica; como tal, ejerció un enorme influjo en toda la narrativa europea. Por considerarse «el mejor trabajo literario jamás escrito», encabezó la lista de las mejores obras literarias de la historia, que se estableció con las votaciones de cien grandes escritores de 54 nacionalidades a petición del Club Noruego del Libro en 2002; así, fue la única excepción en el estricto orden alfabético que se había dispuesto.4 """,
    "et": """"Don Quijote" (täielik pealkiri "Teravmeelne hidalgo Don Quijote La Manchast", hispaania "El ingenioso hidalgo don Quijote de la Mancha"; algselt "El ingenioso hidalgo don Quixote de la Mancha") on Miguel de Cervantese romaan.

Romaan ilmus kahes osas – esimene aastal 1605, teine – 1615. 1939.–1940. aastal jõudis eesti keelde Aita Kurfeldi tõlkes esimene täielik väljaanne "Don Quijote" esimesest osast, sellele järgnes 1947. aastal teine osa.[1]"Don Quijote" on teine kõige tõlgitum teos Piibli järel.[2]

"Don Qujiote" on kirjutatud rüütliromaanide paroodiana, mis olid tol ajal Hispaanias levinud. Rüütliromaanid käsitlesid igavesi teemasid, nagu armastus, lahusolek, surm, reetmine, hea ja kurja võitlus. Kogu tegevus toimus ideaalses maailmas, kus kõik võimatu oli võimalik. "Don Quijote" vaatab sellele kirjandusžanrile kriitilise-satiirilise pilguga.[3] """,
    "fi": """Don Quijote, koko nimeltään Neuvokas ritari don Quijote Manchalainen (esp. El ingenioso hidalgo Don Quijote de la Mancha), on espanjalaisen Miguel de Cervantesin (1547–1616) kahtena niteenä vuosina 1605 ja 1615 ilmestynyt veijariromaani. Sitä pidetään nykyaikaisen romaanitaiteen perustajana ja yhtenä maailmankirjallisuuden suurista klassikoista.[1][2] """,
    "fr": """L’Ingénieux Hidalgo Don Quichotte de la Manche ou L'Ingénieux Noble Don Quichotte de la Manche (titre original en espagnol El ingenioso hidalgo don Quixote de la Mancha ; en espagnol moderne : El ingenioso hidalgo don Quijote de la Mancha) est un roman écrit par Miguel de Cervantes et publié à Madrid en deux parties, la première en 1605 puis la seconde en 1615.

À la fois roman médiéval — un roman de chevalerie — et roman de l'époque moderne alors naissante, le livre est une parodie des mœurs médiévales et de l'idéal chevaleresque, ainsi qu'une critique des structures sociales d'une société espagnole rigide et vécue comme absurde. Don Quichotte est un jalon important de l'histoire littéraire et les interprétations qu'on en donne sont multiples : pur comique, satire sociale, analyse politique. Il est considéré comme l'un des romans les plus importants de la littérature mondiale et comme le premier roman moderne.

Le personnage, Alonso Quichano, est à l'origine de l'archétype du Don Quichotte, personnage généreux et idéaliste qui se pose en redresseur de torts.
""",
    "it": """Don Chisciotte della Mancia (El Ingenioso Hidalgo Don Quijote de la Mancha) è un romanzo spagnolo di Miguel de Cervantes Saavedra, pubblicato in due volumi, nel 1605 e 1615. È annoverato non solo come la più influente opera del Siglo de Oro e dell'intero canone letterario spagnolo, ma un capolavoro della letteratura mondiale nella quale si può considerare il primo romanzo moderno. Vi si incontrano, bizzarramente mescolati, sia elementi del genere picaresco sia del romanzo epico-cavalleresco, nello stile del Tirant lo Blanch e del Amadís de Gaula. I due protagonisti, Alonso Chisciano (o Don Chisciotte) e Sancho Panza, sono tra i più celebrati personaggi della letteratura di tutti i tempi.

Il pretesto narrativo ideato dall'autore è la figura dello storico Cide Hamete Benengeli, di cui Cervantes dichiara di aver ritrovato e fatto tradurre il manoscritto arabo, nel quale sono raccontate le vicende di Don Chisciotte.[1] Oltre l'artificio letterario dal forte valore parodico, l'invenzione di questo narratore inaffidabile e di altri filtri narrativi destinati a creare ambiguità nel racconto è una delle più fortunate innovazioni introdotte da Cervantes.

L'opera di Cervantes fu pubblicata nel 1605 quando l'autore aveva 57 anni. Il successo fu tale che Alonso Fernández de Avellaneda, pseudonimo di un autore fino ad oggi sconosciuto, pubblicò la continuazione nel 1614. Cervantes, disgustato da questo sequel, decise di scrivere un'altra avventura del Don Quijote - la seconda parte - pubblicata nel 1615. Con oltre 500 milioni di copie, è il romanzo più venduto della storia.[2] """,
    "nl": """Don Quichot (Spaans: Don Quijote of Quixote) is de hoofdpersoon in de door Cervantes geschreven roman De vernuftige edelman Don Quichot van La Mancha. Deze roman bestaat uit twee delen: het eerste werd gepubliceerd in 1605, het tweede in 1615.

Het boek is een van de eerste geschreven romans in een moderne Europese taal. Het vertelt de komische reisavonturen van een oude edelman die denkt dat hij een dolende ridder is. Deze hoofdpersoon, Don Quichot, is het stereotype van de idealist, een dwaze held die zich met zijn goede bedoelingen maar onpraktische daden min of meer belachelijk maakt. """,
    "ru": """«Хитроу́мный ида́льго Дон Кихо́т Лама́нчский» (исп. El ingenioso hidalgo Don Quijote de la Mancha), часто просто «Дон Кихо́т» — роман испанского писателя Мигеля де Сервантеса Сааведра (1547—1616) о приключениях одноимённого героя. Был опубликован в двух томах. Первый вышел в 1605 году, второй — в 1615 году. Роман задумывался как пародия на рыцарские романы.

Впоследствии переведённый на все европейские языки [источник не указан 163 дня], этот роман является одной из популярнейших книг мировой литературы. Он входит во Всемирную библиотеку (список наиболее значимых произведений мировой литературы Норвежского книжного клуба) как «лучшая книга всех времён и народов». """,
    "sk": """Dômyselný rytier Don Quijote de la Mancha (pôvodný španielsky titul: El ingenioso hidalgo Don Quixote de la Mancha, neskôr aj len Don Quijote de la Mancha) [vyslov: don kichote de la manča] je román z roku 1605, ktorý napísal Miguel de Cervantes y Saavedra. Je to satira na rytierske romány, pikareskný román z obdobia renesancie, ktorý uviedol do literatúry komicky vyjadrený rozpor medzi skutočnosťou a ilúziou.

Je to jedno z najčítanejších literárnych diel vôbec a najčítanejšie a najprekladanejšie dielo španielskej literatúry.

Napísal ho jednoruký Cervantes v sevillskom žalári bez zatrpknutosti a s úsmevným humorom, plný múdrosti a lásky k človeku na prahu staroby, po mnohých životných sklamaniach a literárnych neúspechoch. """,
}
